ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.org/mergeable-ingress-type: "minion"
  hosts:
    - host: ${domain}
      paths:
        - path: /sso
          pathType: Prefix

telemetry:
  http: 0.0.0.0:5558

grpc:
  enabled: true

enablePasswordDB: true
oauth2:
  skipApprovalScreen: true

config:
  issuer: http://${domain}/sso
  logger:
    format: json
  storage:
    type: postgres
    config:
      host: ${pg.host}
      port: ${pg.port}
      database: ${pg.database}
      user: ${pg.user}
      password: ${pg.password}
      ssl:
        mode: ${pg.ssl.mode}
  connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: ${creds.github_clientid}
        clientSecret: ${creds.github_clientsecret}
        redirectURI: http://${domain}/sso/callback
